server:
  port: 8080

spring:
  application:
    name: elastic-com.vf.business.service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    baselineOnMigrate: true

security:
  jwt:
    token:
      secret-key: secret
      expire-length: 3600000

api:
  version: api/v1