server:
  port: 8080

spring:
  application:
    name: elastic-com.vf.business.service
  flyway:
    baselineOnMigrate: true

security:
  jwt:
    token:
      secret-key: secret
      expire-length: 3600000

api:
  version: api/v1