server:
  port: ${PORT:8080}

spring:
  application:
    name: elastic-com.vf.business.service
  flyway:
    baselineOnMigrate: true

security:
  jwt:
    token:
      secret-key: secret
      expire-length: 5184000000

api:
  version: api/v1