server:
  port: 80

spring:
  application:
    name: elastic-com.vf.business.service
  datasource:
    maxActive: 50
  flyway:
    baselineOnMigrate: true

security:
  jwt:
    token:
      secret-key: secret
      expire-length: 5184000000

api:
  version: api/v1