# Spring properties
spring:
  application:
    name: elastic-com.vf.business.service
  datasource:
    url: jdbc:postgresql://localhost:5432/docker
    username: docker
    password: docker

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

logging:
  level:
    com.netflix.discovery: INFO
    com.netflix.eureka: INFO